#!/bin/bash
# Convert all images in a directory to PNGs

dir=""
if [ $# -ge 1 ]; then
	dir="$1"
	if not test -d $dir; then 
		echo "Invalid path passed"
		return
	fi
else
	dir="$(pwd)"
fi

files=("$dir"/*)

for path in "${files[@]}"; do
	file="${path##*/}"
	name=${file%.*}
	ext="${file##*.}"
	
	case $ext in
		jpg | jpeg)
			convert $path "$dir/$name.png"
			echo "Created $name.png"
			rm $path
			;;
	esac
done
